// 把原生微信小程序源码（miniprogram-worker）打包成一个 JS 文件供 H5 运行时加载。
// 产物：mp-bundle.js → 定义 window.__MP_FILES__ = { '<相对路径>': '<文件内容>' }。
// 运行时（runtime.js）用一个极简 CommonJS + WXML 编译器把这些源码原样跑成 H5，
// 因此页面的 .js/.wxml/.wxss 全部复用，不重写、不改动业务逻辑。
//
// 用法：node build.mjs   （改了小程序源码后重跑一次即可）
import { readdir, readFile, writeFile, stat } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const here = path.dirname(fileURLToPath(import.meta.url))
const mpRoot = path.resolve(here, '../miniprogram-worker')

const INCLUDE_EXT = new Set(['.js', '.json', '.wxml', '.wxss'])
const SKIP_FILES = new Set(['project.config.json', 'project.private.config.json', 'sitemap.json'])

async function walk(dir, base = '') {
  const out = {}
  for (const name of await readdir(dir)) {
    if (name === 'node_modules' || name.startsWith('.')) continue
    const abs = path.join(dir, name)
    const rel = base ? base + '/' + name : name
    const s = await stat(abs)
    if (s.isDirectory()) {
      Object.assign(out, await walk(abs, rel))
    } else if (INCLUDE_EXT.has(path.extname(name)) && !SKIP_FILES.has(name)) {
      out[rel] = await readFile(abs, 'utf8')
    }
  }
  return out
}

const files = await walk(mpRoot)
const banner =
  '// AUTO-GENERATED by h5-worker/build.mjs — do not edit. Source: platform/miniprogram-worker/\n'
const body = 'window.__MP_FILES__ = ' + JSON.stringify(files) + ';\n'
await writeFile(path.join(here, 'mp-bundle.js'), banner + body)

const list = Object.keys(files).sort()
console.log(`[h5 build] bundled ${list.length} files from miniprogram-worker:`)
for (const f of list) console.log('  ' + f)
