// 侧边栏菜单单一事实源:布局渲染、路由守卫兜底跳转共用
import {
  DataLine,
  OfficeBuilding,
  User,
  Warning,
  PhoneFilled,
  Coin,
  Postcard,
  FolderChecked,
  Connection,
  Tickets,
  Wallet,
  Setting,
  Reading,
  UserFilled,
  Document,
  Stamp,
  Service,
  Medal,
  Notebook,
  TrendCharts,
  Download,
  Link,
  Monitor,
  Message,
  QuestionFilled,
  Key
} from '@element-plus/icons-vue'

export const menus = [
  { path: '/dashboard', label: '运营总览', icon: DataLine, perm: 'dashboard:read' },
  { path: '/companies', label: '企业入驻审核', icon: OfficeBuilding, perm: 'company:read' },
  { path: '/workers', label: '零工管理', icon: User, perm: 'worker:read' },
  { path: '/disputes', label: '争议仲裁', icon: Stamp, perm: 'dispute:read' },
  { path: '/tickets', label: '客服工单', icon: Service, perm: 'ticket:read' },
  { path: '/skills', label: '技能认证审核', icon: Medal, perm: 'skill:review' },
  { path: '/risk', label: '风控预警', icon: Warning, perm: 'risk:read' },
  { path: '/quality', label: '回访与理赔', icon: PhoneFilled, perm: 'risk:read' },
  { path: '/tax', label: '税务工作台', icon: Coin, perm: 'tax:read' },
  { path: '/invoices', label: '发票管理', icon: Postcard, perm: 'tax:read' },
  { path: '/input-invoices', label: '进项发票台账', icon: Notebook, perm: 'tax:read' },
  { path: '/archives', label: '凭证归档', icon: FolderChecked, perm: 'archive:read' },
  { path: '/finance', label: '财务报表中心', icon: TrendCharts, perm: 'finance:read' },
  { path: '/flows', label: '资金流水', icon: Tickets, perm: 'flow:read' },
  { path: '/funds-orders', label: '结算/提现单据', icon: Wallet, perm: 'flow:read' },
  { path: '/exports', label: '导出审批', icon: Download, perm: 'export:approve' },
  { path: '/integrations', label: '外部服务状态', icon: Connection, perm: 'integration:read' },
  { path: '/events', label: '集成事件监控', icon: Link, perm: 'integration:read' },
  { path: '/system-health', label: '系统健康', icon: Monitor, perm: 'integration:read' },
  { path: '/templates', label: '消息中心', icon: Message, perm: 'message:manage' },
  { path: '/help-admin', label: '帮助中心管理', icon: QuestionFilled, perm: 'help:manage' },
  { path: '/configs', label: '业务参数配置', icon: Setting, perm: 'config:read' },
  { path: '/credentials', label: '开放API凭据', icon: Key, perm: 'config:read' },
  { path: '/legal', label: '协议/合同模板', icon: Reading, perm: 'config:read' },
  { path: '/users', label: '用户管理', icon: UserFilled, perm: 'user:read' },
  { path: '/audit', label: '审计日志', icon: Document, perm: 'audit:read' }
]
